CREATE TABLE asp_net_roles (
    id TEXT PRIMARY KEY,
    name VARCHAR(256),
    normalized_name VARCHAR(256),
    concurrency_stamp TEXT
);

CREATE TABLE asp_net_users (
    id TEXT PRIMARY KEY,

    user_name VARCHAR(256),
    normalized_user_name VARCHAR(256),

    email VARCHAR(256),
    normalized_email VARCHAR(256),
    email_confirmed BOOLEAN NOT NULL,

    password_hash TEXT,
    security_stamp TEXT,
    concurrency_stamp TEXT,

    phone_number VARCHAR(256),
    phone_number_confirmed BOOLEAN NOT NULL,

    two_factor_enabled BOOLEAN NOT NULL,

    lockout_end TIMESTAMPTZ,
    lockout_enabled BOOLEAN NOT NULL,
    access_failed_count INTEGER NOT NULL,

    first_name TEXT,
    last_name TEXT,

    group_id INTEGER
        REFERENCES scout_group(id)
        ON DELETE RESTRICT,

    has_enabled_authenticator BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE asp_net_role_claims (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    role_id TEXT NOT NULL
        REFERENCES asp_net_roles(id)
        ON DELETE CASCADE,

    claim_type TEXT,
    claim_value TEXT
);

CREATE TABLE asp_net_user_claims (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id TEXT NOT NULL
        REFERENCES asp_net_users(id)
        ON DELETE CASCADE,

    claim_type TEXT,
    claim_value TEXT
);

CREATE TABLE asp_net_user_logins (
    login_provider VARCHAR(128) NOT NULL,
    provider_key VARCHAR(128) NOT NULL,
    provider_display_name TEXT,

    user_id TEXT NOT NULL
        REFERENCES asp_net_users(id)
        ON DELETE CASCADE,

    PRIMARY KEY (login_provider, provider_key)
);

CREATE TABLE asp_net_user_roles (
    user_id TEXT NOT NULL
        REFERENCES asp_net_users(id)
        ON DELETE CASCADE,

    role_id TEXT NOT NULL
        REFERENCES asp_net_roles(id)
        ON DELETE CASCADE,

    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE asp_net_user_tokens (
    user_id TEXT NOT NULL
        REFERENCES asp_net_users(id)
        ON DELETE CASCADE,

    login_provider VARCHAR(128) NOT NULL,
    name VARCHAR(128) NOT NULL,
    value TEXT,

    PRIMARY KEY (user_id, login_provider, name)
);

CREATE TABLE asp_net_user_passkeys (
    credential_id BYTEA PRIMARY KEY,

    user_id TEXT NOT NULL
        REFERENCES asp_net_users(id)
        ON DELETE CASCADE,

    data JSONB NOT NULL
);

CREATE INDEX idx_asp_net_user_passkeys_user_id
    ON asp_net_user_passkeys(user_id);

CREATE UNIQUE INDEX idx_asp_net_roles_normalized_name
    ON asp_net_roles(normalized_name);

CREATE INDEX idx_asp_net_users_normalized_email
    ON asp_net_users(normalized_email);

CREATE UNIQUE INDEX idx_asp_net_users_normalized_user_name
    ON asp_net_users(normalized_user_name);

CREATE INDEX idx_asp_net_users_group_id
    ON asp_net_users(group_id);

CREATE INDEX idx_asp_net_role_claims_role_id
    ON asp_net_role_claims(role_id);

CREATE INDEX idx_asp_net_user_logins_user_id
    ON asp_net_user_logins(user_id);

CREATE INDEX idx_asp_net_user_claims_user_id
    ON asp_net_user_claims(user_id);

CREATE INDEX idx_asp_net_user_roles_role_id
    ON asp_net_user_roles(role_id);
